package Modelo;
// Generated 16-ago-2019 12:36:09 by Hibernate Tools 4.3.1



/**
 * ActividadempresaId generated by hbm2java
 */
public class ActividadempresaId  implements java.io.Serializable {


     private int cuit;
     private int cuacm;

    public ActividadempresaId() {
    }

    public ActividadempresaId(int cuit, int cuacm) {
       this.cuit = cuit;
       this.cuacm = cuacm;
    }
   
    public int getCuit() {
        return this.cuit;
    }
    
    public void setCuit(int cuit) {
        this.cuit = cuit;
    }
    public int getCuacm() {
        return this.cuacm;
    }
    
    public void setCuacm(int cuacm) {
        this.cuacm = cuacm;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ActividadempresaId) ) return false;
		 ActividadempresaId castOther = ( ActividadempresaId ) other; 
         
		 return (this.getCuit()==castOther.getCuit())
 && (this.getCuacm()==castOther.getCuacm());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCuit();
         result = 37 * result + this.getCuacm();
         return result;
   }   


}


