package Modelo;
// Generated 16-ago-2019 12:36:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Departamentos generated by hbm2java
 */
public class Departamentos  implements java.io.Serializable {


     private int idDepartamento;
     private String nombreDepartamento;
     private Set localidadeses = new HashSet(0);

    public Departamentos() {
    }

	
    public Departamentos(int idDepartamento, String nombreDepartamento) {
        this.idDepartamento = idDepartamento;
        this.nombreDepartamento = nombreDepartamento;
    }
    public Departamentos(int idDepartamento, String nombreDepartamento, Set localidadeses) {
       this.idDepartamento = idDepartamento;
       this.nombreDepartamento = nombreDepartamento;
       this.localidadeses = localidadeses;
    }
   
    public int getIdDepartamento() {
        return this.idDepartamento;
    }
    
    public void setIdDepartamento(int idDepartamento) {
        this.idDepartamento = idDepartamento;
    }
    public String getNombreDepartamento() {
        return this.nombreDepartamento;
    }
    
    public void setNombreDepartamento(String nombreDepartamento) {
        this.nombreDepartamento = nombreDepartamento;
    }
    public Set getLocalidadeses() {
        return this.localidadeses;
    }
    
    public void setLocalidadeses(Set localidadeses) {
        this.localidadeses = localidadeses;
    }




}


