package Modelo;
// Generated 27-ago-2019 12:41:28 by Hibernate Tools 4.3.1



/**
 * Domicilio generated by hbm2java
 */
public class Domicilio  implements java.io.Serializable {


     private DomicilioId id;
     private Empresa empresa;
     private Localidades localidades;
     private Planta planta;
     private Integer piso;
     private String depto;
     private int telefono;
     private String email;
     private String zonificacion;
     private String nroPartida;

    public Domicilio() {
    }

	
    public Domicilio(DomicilioId id, Empresa empresa, Localidades localidades, int telefono, String email, String zonificacion) {
        this.id = id;
        this.empresa = empresa;
        this.localidades = localidades;
        this.telefono = telefono;
        this.email = email;
        this.zonificacion = zonificacion;
    }
    public Domicilio(DomicilioId id, Empresa empresa, Localidades localidades, Planta planta, Integer piso, String depto, int telefono, String email, String zonificacion, String nroPartida) {
       this.id = id;
       this.empresa = empresa;
       this.localidades = localidades;
       this.planta = planta;
       this.piso = piso;
       this.depto = depto;
       this.telefono = telefono;
       this.email = email;
       this.zonificacion = zonificacion;
       this.nroPartida = nroPartida;
    }
   
    public DomicilioId getId() {
        return this.id;
    }
    
    public void setId(DomicilioId id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Localidades getLocalidades() {
        return this.localidades;
    }
    
    public void setLocalidades(Localidades localidades) {
        this.localidades = localidades;
    }
    public Planta getPlanta() {
        return this.planta;
    }
    
    public void setPlanta(Planta planta) {
        this.planta = planta;
    }
    public Integer getPiso() {
        return this.piso;
    }
    
    public void setPiso(Integer piso) {
        this.piso = piso;
    }
    public String getDepto() {
        return this.depto;
    }
    
    public void setDepto(String depto) {
        this.depto = depto;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getZonificacion() {
        return this.zonificacion;
    }
    
    public void setZonificacion(String zonificacion) {
        this.zonificacion = zonificacion;
    }
    public String getNroPartida() {
        return this.nroPartida;
    }
    
    public void setNroPartida(String nroPartida) {
        this.nroPartida = nroPartida;
    }
}


