package Modelo;
// Generated 13-ago-2019 9:35:52 by Hibernate Tools 4.3.1



/**
 * Domicilio generated by hbm2java
 */
public class Domicilio  implements java.io.Serializable {


     private DomicilioId id;
     private Empresa empresa;
     private Planta planta;
     private Integer piso;
     private String depto;
     private String localidad;
     private String cp;
     private int telefono;
     private String email;
     private String zonificacion;
     private Integer nroPartida;

    public Domicilio() {
    }

	
    public Domicilio(DomicilioId id, Empresa empresa, String localidad, String cp, int telefono, String email, String zonificacion) {
        this.id = id;
        this.empresa = empresa;
        this.localidad = localidad;
        this.cp = cp;
        this.telefono = telefono;
        this.email = email;
        this.zonificacion = zonificacion;
    }
    public Domicilio(DomicilioId id, Empresa empresa, Planta planta, Integer piso, String depto, String localidad, String cp, int telefono, String email, String zonificacion, Integer nroPartida) {
       this.id = id;
       this.empresa = empresa;
       this.planta = planta;
       this.piso = piso;
       this.depto = depto;
       this.localidad = localidad;
       this.cp = cp;
       this.telefono = telefono;
       this.email = email;
       this.zonificacion = zonificacion;
       this.nroPartida = nroPartida;
    }
   
    public DomicilioId getId() {
        return this.id;
    }
    
    public void setId(DomicilioId id) {
        this.id = id;
    }
    public Empresa getEmpresa() {
        return this.empresa;
    }
    
    public void setEmpresa(Empresa empresa) {
        this.empresa = empresa;
    }
    public Planta getPlanta() {
        return this.planta;
    }
    
    public void setPlanta(Planta planta) {
        this.planta = planta;
    }
    public Integer getPiso() {
        return this.piso;
    }
    
    public void setPiso(Integer piso) {
        this.piso = piso;
    }
    public String getDepto() {
        return this.depto;
    }
    
    public void setDepto(String depto) {
        this.depto = depto;
    }
    public String getLocalidad() {
        return this.localidad;
    }
    
    public void setLocalidad(String localidad) {
        this.localidad = localidad;
    }
    public String getCp() {
        return this.cp;
    }
    
    public void setCp(String cp) {
        this.cp = cp;
    }
    public int getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(int telefono) {
        this.telefono = telefono;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getZonificacion() {
        return this.zonificacion;
    }
    
    public void setZonificacion(String zonificacion) {
        this.zonificacion = zonificacion;
    }
    public Integer getNroPartida() {
        return this.nroPartida;
    }
    
    public void setNroPartida(Integer nroPartida) {
        this.nroPartida = nroPartida;
    }




}


