package Modelo;
// Generated 27-ago-2019 12:41:28 by Hibernate Tools 4.3.1



/**
 * FormacionDePersonal generated by hbm2java
 */
public class FormacionDePersonal  implements java.io.Serializable {


     private Integer idFormacionPersonal;
     private Planta planta;
     private int cantidadObreros;
     private boolean capacitacionObreros;
     private int cantidadTecnicos;
     private boolean capacitacionTecnicos;
     private int cantidadProfesionales;
     private boolean capacitacionProfesionales;

    public FormacionDePersonal() {
    }

    public FormacionDePersonal(Planta planta, int cantidadObreros, boolean capacitacionObreros, int cantidadTecnicos, boolean capacitacionTecnicos, int cantidadProfesionales, boolean capacitacionProfesionales) {
       this.planta = planta;
       this.cantidadObreros = cantidadObreros;
       this.capacitacionObreros = capacitacionObreros;
       this.cantidadTecnicos = cantidadTecnicos;
       this.capacitacionTecnicos = capacitacionTecnicos;
       this.cantidadProfesionales = cantidadProfesionales;
       this.capacitacionProfesionales = capacitacionProfesionales;
    }
   
    public Integer getIdFormacionPersonal() {
        return this.idFormacionPersonal;
    }
    
    public void setIdFormacionPersonal(Integer idFormacionPersonal) {
        this.idFormacionPersonal = idFormacionPersonal;
    }
    public Planta getPlanta() {
        return this.planta;
    }
    
    public void setPlanta(Planta planta) {
        this.planta = planta;
    }
    public int getCantidadObreros() {
        return this.cantidadObreros;
    }
    
    public void setCantidadObreros(int cantidadObreros) {
        this.cantidadObreros = cantidadObreros;
    }
    public boolean isCapacitacionObreros() {
        return this.capacitacionObreros;
    }
    
    public void setCapacitacionObreros(boolean capacitacionObreros) {
        this.capacitacionObreros = capacitacionObreros;
    }
    public int getCantidadTecnicos() {
        return this.cantidadTecnicos;
    }
    
    public void setCantidadTecnicos(int cantidadTecnicos) {
        this.cantidadTecnicos = cantidadTecnicos;
    }
    public boolean isCapacitacionTecnicos() {
        return this.capacitacionTecnicos;
    }
    
    public void setCapacitacionTecnicos(boolean capacitacionTecnicos) {
        this.capacitacionTecnicos = capacitacionTecnicos;
    }
    public int getCantidadProfesionales() {
        return this.cantidadProfesionales;
    }
    
    public void setCantidadProfesionales(int cantidadProfesionales) {
        this.cantidadProfesionales = cantidadProfesionales;
    }
    public boolean isCapacitacionProfesionales() {
        return this.capacitacionProfesionales;
    }
    
    public void setCapacitacionProfesionales(boolean capacitacionProfesionales) {
        this.capacitacionProfesionales = capacitacionProfesionales;
    }
}


