package Modelo;
// Generated 16-ago-2019 12:36:09 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Nodos generated by hbm2java
 */
public class Nodos  implements java.io.Serializable {


     private int idNodo;
     private String nombreNodo;
     private Set localidadeses = new HashSet(0);

    public Nodos() {
    }

	
    public Nodos(int idNodo, String nombreNodo) {
        this.idNodo = idNodo;
        this.nombreNodo = nombreNodo;
    }
    public Nodos(int idNodo, String nombreNodo, Set localidadeses) {
       this.idNodo = idNodo;
       this.nombreNodo = nombreNodo;
       this.localidadeses = localidadeses;
    }
   
    public int getIdNodo() {
        return this.idNodo;
    }
    
    public void setIdNodo(int idNodo) {
        this.idNodo = idNodo;
    }
    public String getNombreNodo() {
        return this.nombreNodo;
    }
    
    public void setNombreNodo(String nombreNodo) {
        this.nombreNodo = nombreNodo;
    }
    public Set getLocalidadeses() {
        return this.localidadeses;
    }
    
    public void setLocalidadeses(Set localidadeses) {
        this.localidadeses = localidadeses;
    }




}


